name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          lfs: true
      - name: Checkout specific branch of submodule
        run: |
          git submodule update --init --recursive
          cd themes/PaperMod
          git fetch --all
          ggit checkout -t origin/theme

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build Hugo Site
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.HUGO_KEY }}
          publish_dir: ./public
